name: widget_to_img
description: A Flutter package to capture a widget as an image.
version: 0.1.0
# author: Arfi Antasofa <antsf73@gmail.com>
homepage: https://github.com/antsf/widget_to_img
repository: https://github.com/antsf/widget_to_img
issue_tracker: https://github.com/antsf/widget_to_img/issues
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
topics:
  - widget
  - image
  - capture
  - screenshot